import{a as u,S as q,i}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const M="56049130-cda03eac6f8abc94af207a1fe";u.defaults.baseURL="https://pixabay.com/api/";async function f(r,t){const a={key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await u.get("",{params:a})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:n,comments:v,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b>${o}</p>
          <p class="info-item"><b>Views</b>${n}</p>
          <p class="info-item"><b>Comments</b>${v}</p>
          <p class="info-item"><b>Downloads</b>${P}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),$.refresh()}function B(){m.innerHTML=""}function p(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function b(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}const w=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",c=1;const S=15;w.addEventListener("submit",x);O.addEventListener("click",D);async function x(r){if(r.preventDefault(),l=r.currentTarget.elements.userQuery.value.trim(),!l){i.warning({message:"Please enter a search query"});return}c=1,B(),d(),p();try{const t=await f(l,c);if(t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits),t.totalHits>S&&b()}catch{i.error({message:"Something went wrong. Please try again later."})}finally{L(),w.reset()}}async function D(){c+=1,d(),p();try{const r=await f(l,c);h(r.hits),b(),E();const t=Math.ceil(r.totalHits/S);c>=t&&(d(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"Something went wrong."})}finally{L()}}function E(){const r=document.querySelector(".gallery-item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
